v0.2.0 release (see CHANGELOG.md)

diff --git a/mongodb-backup b/mongodb-backup
--- a/mongodb-backup
+++ b/mongodb-backup
@@ -1,88 +1,59 @@
 #!/bin/bash
 #
 #  mongodb-backup is a backup script for MongoDB database
-#  Version : 0.1
-#  Copyright (C) 2013  - Michael Lopez
+#  Version : 0.2
 #
-#  This program is free software: you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation, either version 3 of the License, or
-#  (at your option) any later version.
+#  Apache License, Version 2.0
 #
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
+#  Copyright (C) 2013 - Twenga SA
+#  Copyright (C) 2013 - Michael Lopez <mickael.lopez@gmail.com>
 #
-#  You should have received a copy of the GNU General Public License
-#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#  Licensed under the Apache License, Version 2.0 (the "License");
+#  you may not use this file except in compliance with the License.
+#  You may obtain a copy of the License at
+#
+#  http://www.apache.org/licenses/LICENSE-2.0
+#
+#  Unless required by applicable law or agreed to in writing, software
+#  distributed under the License is distributed on an "AS IS" BASIS,
+#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+#  See the License for the specific language governing permissions and
+#  limitations under the License.
 #
 ###########################################################################
+
+############################################################################
+#      Please edit /etc/mongodb-backup.conf according to your needs       #
 ###########################################################################
-#            Set the following variables to your system needs             #
-#                (Detailed instructions below variables)                  #
-###########################################################################
+
 PROGNAME=$(basename $0)
 DATE=$(date +%Y-%m-%d)
-NB_ERRORS=0
+CONF="/etc/mongodb-backup.conf"
 PID_FILE="/var/run/mongodb-backup.pid"
-DUMP_OPTIONS="--journal"
 STOP_BALANCER_JS="/usr/local/lib/stopBalancer.js"
+DUMP_OPTIONS=""
 OPTIONS=""
+NB_ERRORS=0
 NB_FILE=0
 
-## Backup general settings 
-BACKUP_DIR="/var/backups/mongodb"
-LOGS_DIR="${BACKUP_DIR}/logs"
+## Check if mongo binary is present
+which mongo &> /dev/null ; isInstalled=$?
+
+if [ "$isInstalled" == 1 ] ; then
+	echo -e "\nCan't find mongodb client... aborting!"
+	exit 1
+fi
+
+## Check if /etc/mongodb-backup.conf is present
+if [ ! -s "$CONF" ] ; then
+	echo -e "\n$CONF is missing or empty... failed!"
+	exit 1
+else
+	source $CONF
+fi	
+
+## Log file 
 LOG_FILE="${LOGS_DIR}/mongodb-backup_${DATE}.log"
-# Level backup tarball compression
-# Default is normal. Requires values : fast (-1), normal (-5) or best (-9)
-COMPRESS_LVL="normal"
-
-## Display all errors on stdout
-## Default is false
-DISPLAY_ERRORS=true
-
-## Define Mongos host. If you don't use default port, add port number after hostname (e.g "localhost:27019")
-## Default is "localhost"
-## if you need to use remote mongos, add mongos port after hostname (e.g. mongos-01:27017)
-MONGOS_HOST="localhost"
-
-## Enter number of shards you need to backup
-## Default is empty
-NB_SHARD=""
-
-## Enter shard's names.
-## Ex:
-## SHARD1_NAME="s1"
-## SHARD2_NAME="s2"
-## ...
-
-## Enter host or ip address of shards with mongod port
-## Ex:
-## SHARD1_HOST="host-01:27018"
-## SHARD2_HOST="host-02:27018"
-## ...
-
-## Username to access the mongo server e.g. dbuser
-## Unnecessary if authentication is off
-## USERNAME=""
- 
-## Username to access the mongo server e.g. password
-## Unnecessary if authentication is off
-## PASSWORD=""
-
-## Define maximum retention of backup
-## Default is 10
-MAX_RETENTION=10
-
-## Email settings
-## Enable/Disable reporting
-## Default is false
-REPORT=false
-## Define administrator email for report
-REPORT_MAIL=""
-
 
 
 ###########################################################################
@@ -90,14 +61,21 @@ REPORT_MAIL=""
 ###########################################################################
 
 function usage() {
-        echo "Usage: $PROGNAME -h (help)"
+	echo -e "Usage: $PROGNAME [options] ...\n"
+        echo "Options are..."
+	echo -e "   -h \t Display this help message"
+	echo -e "   -j \t Enable dump journalisation"
+	echo -e "   -e \t Display events to STDOUT"
+	echo -e "   -m <mail_address> \t Set email reporting address"
+	echo -e "   -c <compression_level>\t Override compression level: normal, fast or best (default: normal)"
+	echo -e "   -u <username>" 
+	echo -e "   -p <password>"
 }
-
 
 function log {
 	echo -e "$(date +%D" "%T) $1" >> $LOG_FILE
 	if [ "$DISPLAY_ERRORS" ] ; then
-	       echo $1	
+	       echo -e "$1"	
 	fi       
 }
 
@@ -105,7 +83,7 @@ function check_running {
 	if [ -f $PID_FILE ] ; then
 		PID=$(cat $PID_FILE)
 		ps -A | grep $PID &> /dev/null ; isRunning=$?
-		if [ "$isRunning" -eq 0 ] ; then
+		if [ "$isRunning" -eq "0" ] ; then
 			return 0
 		else
 			rm -f $PID_FILE
@@ -122,7 +100,7 @@ function check_is_master {
 
 function pickup_secondary {
 	slaves=$(mongo --host $1 --eval "printjson(rs.status())" | grep -B3 SECONDARY | grep name | sed 's/[\t",]//g' | awk '{print $3}')
-	slave=$(shuf -e $SLAVES -n 1)
+	slave=$(shuf -e $slaves -n 1)
 	echo $slave
 }
 
@@ -153,15 +131,25 @@ function prepare_job {
 		MONGOS_OPT="${OPTIONS} --host ${MONGOS_HOST}"
 	fi
 
-	if [ "$NB_SHARD" != "" ] ; then
+	# Try to connect
+	mongo $MONGOS_OPT --eval "printjson()" &> /dev/null ; tryConnection=$?
+	if [ "$tryConnection" -eq 1 ] ; then
+		log "Critical: Unable to connect on ${MONGOS_HOST}. Please check if mongos is running or check 'MONGOS_HOST' option in /etc/mongodb-backup.conf"
+		exit 1
+	fi
+
+
+	if [ "$NB_SHARD" -ne 0 ] ; then
 		for (( n=1; n<=$NB_SHARD; n++ )) ; do
 			SHARD_HOSTS[$n]=$(eval "echo \$SHARD${n}_HOST")
 			SHARD_NAMES[$n]=$(eval "echo \$SHARD${n}_NAME")
+
+			# Check if value of SHARD_* array is not empty
+			if [ "${SHARD_HOSTS[$n]}" == "" ] || [ "${SHARD_NAMES[$n]}" == "" ] ; then
+				log "Critical: Wrong shard configuration in /etc/mongodb-backup.conf file. Please check the shard options in file."
+				exit 1
+			fi
 		done
-		if [ "$NB_SHARD" -ne "${#SHARD_HOSTS[@]}" ] && [ "${#SHARD_HOSTS[@]}" -ne "${#SHARD_NAMES[@]}" ]; then
-			errorMsg="Critical: Wrong backup shard configuration. Please check variable : NB_SHARD must be equal to the number of SHARD_HOST and the number of SHARD_NAME"
-			log $errorMsg ; echo $errorMsg; exit 1
-		fi
 		log "Info : ${NB_SHARD} shard has been selected for backup."
 	fi
 }
@@ -196,13 +184,13 @@ function do_tarball {
 }
 
 function check_retention {
-	if [ $MAX_RETENTION -gt "0" ] ; then
+	if [ $MAX_BACKUP_RETENTION -gt 0 ] ; then
     		log "Checking retention of backups..."
-    		toDelete=$(find $BACKUP_DIR -name "*.tar.gz" -type f -mtime +$MAX_RETENTION)
+    		toDelete=$(find $BACKUP_DIR -name "*.tar.gz" -type f -mtime +$MAX_BACKUP_RETENTION)
       		if [ ! -z "$toDelete" ] ; then
-        		log "Deleting files older than ${MAX_RETENTION} days:"
-        		find $BACKUP_DIR -name "*.tar.gz" -type f -mtime +$MAX_RETENTION -exec du -hs {} \; >> $LOG_FILE
-       			find $BACKUP_DIR -name "*.tar.gz" -type f -mtime +$MAX_RETENTION -exec rm {} \;
+        		log "Deleting files older than ${MAX_BACKUP_RETENTION} days:"
+			log "$(find $BACKUP_DIR -name "*.tar.gz" -type f -mtime +$MAX_BACKUP_RETENTION -exec du -hs {} \;)" 
+       			find $BACKUP_DIR -name "*.tar.gz" -type f -mtime +$MAX_BACKUP_RETENTION -delete
       		fi
 	else
 		log "Info : Retention is disable."
@@ -210,7 +198,7 @@ function check_retention {
 }
 
 function send_mail {
-	if [ "$REPORT" ] ; then
+	if [ "$REPORT_EMAIL" ] && [ -n ${REPORT_EMAIL+x}  ] ; then
 		log "Sending email notifications..."
 	    	echo "Backup time: $TIME_DIFF minutes" > /tmp/$PROGNAME_mail.tmp
 	    	echo -e "disk usage:  (size : usage : avail : percent : parent) \n $(df -h $BACKUP_DIR | tail -1)" >> /tmp/$PROGNAME_mail.tmp 
@@ -224,9 +212,9 @@ function send_mail {
 	        echo -e "\nnumber of erros/warning : $NB_ERRORS \nCheck log file for more details : $LOG_FILE" >> /tmp/$PROGNAME_mail.tmp
 	   	
 		SUBJECT="[MongoDB Backup] Report -> Host:  $(hostname) - errors: $NB_ERRORS - runtime: $TIME_DIFF minutes"
-	      	mail -s "$SUBJECT" "$REPORT_MAIL" < /tmp/$PROGNAME_mail.tmp
+	      	mail -s "$SUBJECT" "$REPORT_EMAIL" < /tmp/$PROGNAME_mail.tmp
 	        if [ $? -eq "0" ] ; then
-	        	log "Email notification successfully sent..."
+	        	log "Email notification successfully sent."
 	        fi
 	      	rm -f /tmp/$PROGNAME_mail.tmp
 	fi
@@ -272,20 +260,49 @@ function get_balancer_state {
 }
 
 ###########################################################################
-#                              Startup checks                             #
+#                              Options checks                             #
 ###########################################################################
 
-if [ $# -gt 1 ] ; then
-        usage
-        exit 1
-fi
-
-while getopts ":h" opt ; do
+while getopts ":hjerm:c:u:p:" opt ; do
         case "$opt" in
 		h) usage >&2 ; exit 0;;
-		\?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
+		j) DUMP_OPTIONS="--journal" >&2
+		;;	
+		e) DISPLAY_ERRORS=true >&2
+		;;
+		m) REPORT_EMAIL=$OPTARG >&2
+		;;	
+		c) COMPRESS_LVL=$OPTARG >&2
+		;;	
+		u) USERNAME=$OPTARG >&2
+		;;
+		p) PASSWORD=$OPTARG >&2 
+		;; 	
+		\?) echo "Invalid option: -$OPTARG" >&2
+		exit 1;;
+		:)  echo "Option -$OPTARG requires an argument." >&2
+		exit 1;;
 	esac
 done
+
+## Check email 
+if [ "$REPORT_EMAIL" ] && [ -n ${REPORT_EMAIL+x} ] ; then
+	CHECK_EMAIL=$(echo $REPORT_EMAIL | egrep "^(([-a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~])+\.)*[-a-zA-Z0-9\!#\$%\&\'*+/=?^_\`{\|}~]+@\w((-|\w)*\w)*\.(\w((-|\w)*\w)*\.)*\w{2,4}$")
+	if [ "x$CHECK_EMAIL" = "x" ]; then 
+		echo -e "\nInvalid email format...failed!"
+		usage
+		exit 1
+	fi	
+fi
+
+## Check compression lvl
+if [ "$COMPRESS_LVL" != "normal" ] && [ "$COMPRESS_LVL" != "fast" ] && [ "$COMPRESS_LVL" != "best" ] ; then
+	echo -e "\nBad compression level... what did you do ?!"
+	echo "Valid values: fast, normal or best"
+	usage
+	exit 1
+fi
+
 
 ###########################################################################
 #                                   BEGIN                                 #
@@ -294,8 +311,8 @@ done
 check_running ; isRunning=$?  
 
 if [ "$isRunning" -eq 0 ] ; then
-	MSG="MongoDB backup is already running"
-	log $MSG ; echo $MSG ; exit
+	log "MongoDB backup is already running"
+	exit
 else
 	echo "$$" > $PID_FILE
 	START_TIME=$(date +%s)
@@ -317,14 +334,14 @@ else
         	log "Error : CFG backup failed !"
 		let NB_ERRORS++
         fi
-	if [ "$NB_SHARD" != "" ] ; then 
+	if [ "$NB_SHARD" -ne "0" ] ; then 
 		i=1
 		for SHARD in ${SHARD_HOSTS[@]} ; do 
 			isMaster=$(check_is_master $SHARD)
 			if [ "$isMaster" == "true" ] ; then
 				log "${SHARD} is master of replicaSet. Pickup a slave host..."
 				SHARD=$(pickup_secondary $SHARD)
-				log "...${SHARD} has been selected."
+				log "${SHARD} has been selected."
 			fi
 			mongodump --host $SHARD $OPTIONS $DUMP_OPTIONS --oplog --out $BACKUP_DIR/$(eval "echo \$SHARD${i}_NAME") &> /dev/null ; SHARD_RETURN=$?	
 			DIRECTORIES[$i]=$(eval "echo \$SHARD${i}_NAME")
